name: Docker Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron:  '0 4 * * SAT'

jobs:

  build:

    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code into workspace directory
      uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build .
    - name: Run CI tests
      run: bash ./utils/runTests.sh
      env:
        GOROOT: /usr/local/go
        GOPATH: /root/go
        PATH: /root/go/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin